jobs:
  tag:
    steps:
      - name: Tag latest commit
        uses: dycw/action-tag-commit@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
name: push
"on":
  push:
    branches:
      - master
